-- my-test-data.sql

INSERT INTO MISSIONS (STARTDATE, ENDDATE, TYPE) VALUES ('1970-01-01', '1972-05-04', 'ASSASSINATION');
INSERT INTO MISSIONS (STARTDATE, ENDDATE, TYPE) VALUES ('1970-01-03', '1972-05-04', 'SABOTAGE');

INSERT INTO SPIES (FIRSTNAME, LASTNAME, CODENAME) VALUES ('Jozo', 'Férový', 'Nunu Pu', 1);
INSERT INTO SPIES (FIRSTNAME, LASTNAME, CODENAME) VALUES ('Féro', 'Jožový', '3.14', 2);